### ISSUE TITLE
sortable list example [lists]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-shopping-list-template#114]
https://gist.github.com/atherdon/74eaf433eee18b03317dc61909a90a13

**Comment by atherdon** [comment]
@vadim9999 check and try to move this sample to our project. i want to see how it works

**Comment by vadim9999** [comment]
https://github.com/GroceriStar/react-shopping-list-template/pull/159

**Comment by atherdon** [comment]
ok, merging

**Comment by vadim9999** [comment]
ok

**Comment by atherdon** [comment]
last merge was related to departments, then we have left sortable list with ingredients, right?

**Comment by atherdon** [comment]
done
