### ISSUE TITLE
[lists][alpha]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-shopping-list-template#115]
я немного пока делаю курс - переделал list.
я его сейчас залью в отдельный проект
тебе нужно будет скачать себе его репозиторий
потом сделать стандартный npm publish потому что последние коммиты не на npm
а потом установить этот плагин на этот проект и вывести информацию

название @groceristar/grocery-component
https://www.npmjs.com/package/@groceristar/grocery-component
а репо https://github.com/GroceriStar/grocery-react-component

пример как я использую этот dumb component
https://github.com/GroceriStar/showcase/blob/master/src/views/HomeView.js#L12

**Comment by atherdon** [comment]
1) увидеть в репозитории grocery-react-component компоненты для листа
2) впринципе можно будет потом удалить TodayDate - я его использовал чтобы понять что код будет работать.
3) я сделал билд, поэтому его можно не делать. до конца работа билда не отлажена - поэтому легче всего билд запускать с помощью `yarn install` так он точно запустится.
4) залогинится в npm и сделать publish проекта. поидее у тебя все права должны быть для этого
5) установить плагин в наш проект и попробывать вывести лист с его помощью

**Comment by vadim9999** [comment]
@atherdon I have execute command `yarn install`. How to run this plugin?

**Comment by vadim9999** [comment]
Component TodaysDate works. List and DefaultList doesn`t work.
```
import { DefaultList, List, TodaysDate } from "@groceristar/grocery-component";
<List items={["One", "Two", "Three", "Apple"]} renderItem={"Two"}/>
<DefaultList items={["One", "Two", "Three", "Apple"]} renderItem={"One"}/>
```

**Comment by atherdon** [comment]
did you publish next version at npm?

**Comment by atherdon** [comment]
i think you did.
are you install the latest version to this repo? will check it myself, hold on

**Comment by atherdon** [comment]
you'll need to install this plugin first - then i hope it will work
