### ISSUE TITLE
install create-react-app and create router with this separated list of pages

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-shopping-list-template#2]
https://github.com/GroceriStar/react-shopping-list-template/invitations

Groceristar sitemap: https://groceristar.gitbook.io/documentation/gs-sitemap

**Comment by NeerajDana** [comment]
Arthur can you send me a detail document please that will be much helpfull for me

**Comment by atherdon** [comment]
@NeerajDana it's a hard thing. i mean - i can put as much data as i can - but you'll still be able to tell that this is not clear :)

**Comment by atherdon** [comment]
@NeerajDana check this and tell me is this enough for start: https://groceristar.gitbook.io/documentation/ ?

**Comment by atherdon** [comment]
if you want to start - help me - let's start a discussion, where we'll explore together, what exactly do you need, ok?

**Comment by AminuSufi585** [comment]
Hi, @atherdon I'll start this. I'll check out react-router first.

**Comment by atherdon** [comment]
@NeerajDana @AminuSufi585 if we'll start this project fast and i'll a lot of a progress - i'll be able to join a development process and code myself too, and this will help you with small tasks, that will require my advanced knowledge of the previously built system

Btw, i add some additional information to our documentation portal: https://groceristar.gitbook.io/documentation/shop-list-information/templates-that-we-have-in-our-previous-esjs-jade-version

**Comment by AminuSufi585** [comment]
Great!

**Comment by AminuSufi585** [comment]
Hi, @atherdon I had learned the basics of the client-side routing. Now I want to know exactly what I should do. Check the code I recently pushed to the repo and give me a feedback and the next steps :)

**Comment by atherdon** [comment]
0) i didnt see anything that you've pushed. maybe you forgot to create a pull request to main repository?
1) create set of empty pages(components), nothing inside, that stated in our documentation.
And connect that components to your router, so by switching URL we'll call a different components
2) install `raven-js`, `underscore`, `@groceristar/groceristar-fetch` plugins in our project

**Comment by AminuSufi585** [comment]
0. Sorry I forgot to create a pull request, I have done so now
1. I'll do just that, but check my pull request and give me feedback whether its correct or not
2. I'll do that as well

**Comment by atherdon** [comment]
don't worry - it's fine. Btw, it's my job to check everything :)
1. make some comments. nothing complex to change
2. push it into this pull request too
More fun will be soon :)

**Comment by AminuSufi585** [comment]
I have continued working on it.

**Comment by atherdon** [comment]
good to know


On 17-Jul-2018 at 07:42 PM, Aminu Ibrahim Abubakar wrote:


I have continued working on it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-shopping-list-template/issues/2#issuecomment-405703984>,
or mute the thread

**Comment by AminuSufi585** [comment]
Hi @atherdon,
I'm comfortable enough with the technology now. Been reading more about it for several days. More especially the design pattern in React. Is there any UI design that I should do my styling with?

If I need any other thing else, I'll ask for it. But that is what I need for now.

**Comment by atherdon** [comment]
for now - i don't have a good idea which UI to pick.
i mean i have a long list of react UI starters, but it's hard to pick one, because i should put my hands into them

**Comment by atherdon** [comment]
do you have a tasks for next steps in this repo? just not remember it :)

Btw, i have a long story working with Bootstrap. So if you'll install reactstrap and use it - i'll be easy for me to help you.

More about UI kits. For module, where we're creating an advanced search form we decided to use Antd, and it looks like pretty good framework, but when you start to dig more and more inside it - you figure out that it has a lot of troubles inside. complex funcxtionality starting to look very complicated. So i think soon or later we'll switch from Antd for that module - because when you did at least 100 commits by using UI kit - you start to know more about it.

**Comment by AminuSufi585** [comment]
I'll use the Bootstrap then. But is there any difference between the **reactstrap** and **react-bootstrap**? Trying to Google it out, the two shows up. 

And for the UI, I'm talking about how the interface should look like? An image of it will suffice. I'm going going to build it up from scratch using the create-react-app I had installed earlier.

**Comment by atherdon** [comment]
reactstrap related to latest version of bootstrap(4)

**Comment by atherdon** [comment]
ok, i think i owe you some details :)
Here is the screens of how our project looks at previous versions: https://groceristar.gitbook.io/documentation/gs-shoplist-screens
This is a sitemap, related to current version of project that we have: https://groceristar.gitbook.io/documentation/gs-sitemap
This is a list of methods that we have in our current api server: https://groceristar.gitbook.io/documentation/groceristar-website-methods-list
some additional data also here: https://groceristar.gitbook.io/documentation/shop-list-information/templates-that-we-have-in-our-previous-esjs-jade-version

i didn't have time/passion to finish it and make it to looks good, but i think it'll give you a preliminary idea, about what you should do at least for a first steps.

Btw, please install `@groceristar/groceristar-fetch` plugin - we create a separated module, where we're storing a static data, related to our projects. So for a first steps, you wouldn;t need to connect to our database in order to display a list of items. More will explain later. 
Few days ago we completed a part of that module related to groceristar project. 
You can read more about how it works in our readme: https://github.com/GroceriStar/groceristar-fetch
