### ISSUE TITLE
[Components][Ingredient]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-shopping-list-template#66]
we'll have a set of simple components, related to ingredients. Later i'll explain the reasons
list:
- simple text(or label)
- text with id 
- Checkbox, label, id, Edit link, Delete link
- list element(part of Ingredient list)
- editable label for ingredient
- part of selectbox
- label, id, order, status

**Forms**
- Create New Ingredient Form(Simple version)
- Create New Ingredient Form with adding result to the ingredient list
- Form with Autocomplete version

**Comment by vadim9999** [comment]
I am working on it

**Comment by atherdon** [comment]
don't forget to pull changes frequently. because I'm working on the structure updates @vadim9999

**Comment by atherdon** [comment]
plus create separated page where we can see all of this components at one page as sample

**Comment by atherdon** [comment]
**Delete Link** should have some method at components. actually it will be a a handler of onClick, please add it, as well to **Edit Link** too

Maybe also instead of <a> we can use react-dom **Link**? tell me what do you think

**Comment by atherdon** [comment]
this was a task that you were working on @vadim9999 ?

**Comment by atherdon** [comment]
are we finish it?

**Comment by vadim9999** [comment]
Our need to add forms

**Comment by vadim9999** [comment]
will It be a input with dropdown menu or just selectbox with ingredients?

**Comment by atherdon** [comment]
it's a autocomplete - i assume selectbox @vadim9999

**Comment by vadim9999** [comment]
@atherdon I think we can close this issue
